### ISSUE TITLE
Dock Ignores Fullscreen applications/games

### ISSUE THREAD

**Issue by joshagosh** [icedman/dash2dock-lite#142]
I have to currently re-install Manjaro on my laptop, but before the installation got corrupt (thanks displaylink drivers) I was experiencing the dock not hiding in full screen mode. I plan on getting my laptop imaged tonight and if that issue is still persistent, I will upload photos here.  A temporary solution for this is enabling pressure sense, but it's not a 100% fix, I'd say it's a 90% bandaid fix since when play games like first person shooters you can still trigger the dock by moving your pointer down. As stated earlier This is just to keep the issues tracked, once I get my system set back up and I'll upload prevalent photos to this thread.

Current games affected/tested: 
Team Fortress 2
Apex Legends
Black Mesa
Half Life 2
Plague Inc

**Comment by joshagosh** [comment]
Update: I have my laptop running to at least be usable I'll worry about theming it later.  It turns out this bug is happening with Disable unredirect fullscreen windows by kazimieras.vaina. This tends to be a popular extension for nvidia users who experience screen tearing in gnome shell. I honestly don't know if this extension is honestly even needed anymore with a distribution like Manjaro, but the conflict with that extension is there. As stated in my original post pressure sense hides the dock, but it is most certainly not a permanent solution. I'm going to test youtube videos as well with these two extensions and see if it's just related to games or a system wide phenomena 


![Screenshot from 2024-05-10 22-15-16](https://github.com/icedman/dash2dock-lite/assets/145363336/1778ab69-e850-40b8-91e9-d1dec527400d)
![Screenshot from 2024-05-10 22-15-39](https://github.com/icedman/dash2dock-lite/assets/145363336/030ef24c-bbae-4cbc-a833-4ef1dfe6a13b)

**Comment by joshagosh** [comment]
It appears as though disabling it glitches the extension. As I am still learning code, and more of a tester than a developer I'd advise users to avoid  Disable unredirect fullscreen windows in the mean time if possible until a full fix is developed.
![Screenshot from 2024-05-11 00-38-06](https://github.com/icedman/dash2dock-lite/assets/145363336/2a806d0a-c780-4736-9ad0-2b8552d738c6)
![Screenshot from 2024-05-11 00-39-12](https://github.com/icedman/dash2dock-lite/assets/145363336/e34aca00-0121-4502-b9e3-7a60fe0f6104)

**Comment by icedman** [comment]
I can re-create the bug simply with mplayer playing a video at fullscreen.  I've pushed a fix on the development branch that fixes with mplayer. Please check if this works with the game. (I don't have any games installed on my laptop)

**Comment by joshagosh** [comment]
I have the developmental branch installed with auto hide and dodge only enabled. The bug seems to be non-existent with these settings enabled. I believe on the stable version I only had dodge enabled. With auto hide disabled the same thing happens in developmental. Auto hide with dodge enabled is a much more simpler solution that using pressure since and mitigates the dock randomly popping up while also maintaining functionality. Once I get my Linux desktop set up tomorrow evening I'll report back with some more testing on the stable branch with these settings.

**Comment by joshagosh** [comment]
I've come across some personal life matters I have to take care of. Once those are done I will get to getting the desktop up and running.  With my last entry, the bug kind of disappears, if you go to where your dock is positioned and click near it in a full screen application it still shows up.

**Comment by icedman** [comment]
I'm getting busy myself these days. I will still try to fix bugs over weekends. Just post whatever information you can. Thanks.

**Comment by joshqou** [comment]
Duplicate of #131

**Comment by joshagosh** [comment]
I got the desktop up and running with the non-development release of the extension installed. These same issues I have been having on my laptop are persistent with the latest non-development release.  A temporary solution I have found for others having this issue is if you're playing first-person shooters with a mouse and keyboard enable dodge, hide and pressure sense. Try not to full ham on the mouse movement as well with full-screen applications. Cuz it will trigger the dock to pop up. I have a sneaking suspicion that this might have something to do with imagemagick, I actually have a feature request I will submit after this that pertains to it as well. Needless to say same issue, but temporary solution is enable dodge, hide and pressure sense to keep the dock hidden in fullscreen mode.

**Comment by joshagosh** [comment]
Hello! I know I've fallen off the face of the earth and I apologize for that. I am finalizing stuff to get ready for Uni. The enrollment process and all the other things I have had to do for the last month have consumed most of my time. as of current (July 22nd, 2024) I am still facing this bug, however, it could be because I am running a month-old version of the extension and haven't read through all the tickets submitted in the last month. Once I have some time this Sunday I plan on wiping both machines and starting fresh.

**Comment by joshagosh** [comment]
> Hello! I know I've fallen off the face of the earth and I apologize for that. I am finalizing stuff to get ready for Uni. The enrollment process and all the other things I have had to do for the last month have consumed most of my time. as of current (July 22nd, 2024) I am still facing this bug, however, it could be because I am running a month-old version of the extension and haven't read through all the tickets submitted in the last month. Once I have some time this Sunday I plan on wiping both machines and starting fresh.

Update: similar issue even with the latest extension. I'm going to chalk it up to some weird tech stuff and say it'll be best to enable hide and dodge along with pressure sense if any user needs a consistent full-screen experience. It's a bandaid solution, but it works until I have more time to document what's happening. Ideally, it's a non-issue when the bandaid solution is applied I mentioned earlier.
