### ISSUE TITLE
Issue: Icons shake maybe due to minute difference in icon sizes

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#41]
With earlier changes dock seems fixed to me on adjacent items, but with 2-5  nearby icons  it has still some effect, could be maybe due to dock spreads its width but since icons are of different size with minute difference it gives shaking effect as you keep moving cursor across the dock.
Checkout is of development branch.
Can it be possible to neutralize the size of the icons excluding the alpha channel, wherever color boundary of icons starts and ends.

Video:-
https://drive.google.com/file/d/1aMDVS-Y03hej3nZrGXGaLEDI0NjYRJVw/view?usp=sharing

**Comment by icedman** [comment]
I see the shaking now. It is not very obvious on my laptop :)
Filtering out minute size changes may be possible.

**Comment by Ticklezz** [comment]
I did notice some slight shaking still.

**Comment by icedman** [comment]
The latest d2dl update @ EGO has another attempt achieving a maclike, pixel perfect animation.  So does anino-dock

**Comment by prashantjain25** [comment]
Seems like this has been achieved but a weird issue arise when dock size extend beyond a limit with multiple items, earlier only the item on focus use to magnify.
![Screenshot from 2022-12-29 11-05-08](https://user-images.githubusercontent.com/5137282/209907798-c0c29969-36f6-4e04-9ef0-417d5201ac3a.png)

**Comment by icedman** [comment]
@prashantjain25 latest update should resolve this.

**Comment by prashantjain25** [comment]
there is still one issue that after a point with the icons size greater than 36, shrink has no effect on the spacing between the icons and if we try to compensate by reducing the "spread" on animation there is still no change, the only changes which are visible at this point is "magnification" and "rise"

**Comment by icedman** [comment]
I also placed a cap at magnification and spread so that the cons never overflow the scree . I will look at how macos handles overflowing of icons as our latest algorithm now closely follows the macos implementation.

**Comment by icedman** [comment]
Also, there are some limits to icons sizes depending on how many they are on the screen.. this is also to prevent overflow.

**Comment by prashantjain25** [comment]
Seems fixed now no more dock expanding on minimal settings.
